### ISSUE TITLE
why node_modules folder?

### ISSUE THREAD

**Issue by brunormferreira** [brendonguedes/CRUD_NODEJS#1]
Hello brother, I liked your crud, but why did you push the `node_modules` folder?

And did you think in create a `routes` folder separate from index.js or you really wants to do it? 

Congrats bro! :1st_place_medal:

**Comment by brendonguedes** [comment]
What's up bro?

This was the most appropriate approach for a teaching tutorial, so i sent node_modules.

I didn't think of separating the routes from the index folder. I would love to see your approach, if you like, make these changes and send me at the end. Very cool your interaction, see you soon bro :)

Thank you!

**Comment by brunormferreira** [comment]
Cool! I currently busy with some projects on my company, but, when I finish that things maybe I sent a pull request to you :D good bye man!

Good job and thanks for answer!
